/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/connect`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup-details`; params?: Router.UnknownInputParams; } | { pathname: `/signup-phone`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/busca` | `/busca`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceDetails`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceFinalReview`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceInit`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceLocation`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceOwnerInfo`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceReview`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/connect`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup-details`; params?: Router.UnknownOutputParams; } | { pathname: `/signup-phone`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/busca` | `/busca`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro-servico/RegisterServiceDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro-servico/RegisterServiceFinalReview`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro-servico/RegisterServiceInit`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro-servico/RegisterServiceLocation`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro-servico/RegisterServiceOwnerInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/cadastro-servico/RegisterServiceReview`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/connect${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup-details${`?${string}` | `#${string}` | ''}` | `/signup-phone${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/busca${`?${string}` | `#${string}` | ''}` | `/busca${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `/cadastro-servico/RegisterServiceDetails${`?${string}` | `#${string}` | ''}` | `/cadastro-servico/RegisterServiceFinalReview${`?${string}` | `#${string}` | ''}` | `/cadastro-servico/RegisterServiceInit${`?${string}` | `#${string}` | ''}` | `/cadastro-servico/RegisterServiceLocation${`?${string}` | `#${string}` | ''}` | `/cadastro-servico/RegisterServiceOwnerInfo${`?${string}` | `#${string}` | ''}` | `/cadastro-servico/RegisterServiceReview${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/connect`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup-details`; params?: Router.UnknownInputParams; } | { pathname: `/signup-phone`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/busca` | `/busca`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceDetails`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceFinalReview`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceInit`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceLocation`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceOwnerInfo`; params?: Router.UnknownInputParams; } | { pathname: `/cadastro-servico/RegisterServiceReview`; params?: Router.UnknownInputParams; } | `/+not-found` | `/category/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
